const songs = [
  {
    title: '求神呐 - 柏鹿',
    source: '../images/求神呐.mp3',
    lyrics: [
      " 佛门弟子守住六根清静",
      " 颂经之人但求一颗舍利",
      " 高柱之上神仙俯看生灵",
      " 香火绵延圆满几家希冀",
      " 梨花开又去 庙门前香客拥挤",
      " 赠来一菩提 有人愁有人欢喜",
      " 跪来纵心欲 和尚看遍繁华记",
      " 祈天意 拜地去 三叩首求灵",
      " 香客们看木鱼应出生机",
      " 瞧一瞧人间一出好戏",
      " 求姻缘求得子求君相依",
      " 求一求好像都来得及",
      " 听人泪听人安听人心系",
      " 听一听什么无上奥秘",
      " 太荒诞的世界",
      " 为何还有人会着迷",
      " 神仙啊 菩萨啊 写好剧情",
      " 小弟我真的是受不起",
      " 我祈祷 我求天 保佑顺意",
      " 就是要被人称了不起",
      " 三冬暖 春不寒 此生绚丽",
      " 只愿你拥有的奢侈品",
      " 太奇幻的世界",
      " 让我们如此的着迷",
      " 佛门弟子守住六根清静",
      " 颂经之人但求一颗舍利",
      " 高柱之上神仙俯看生灵",
      " 香火绵延圆满几家希冀",
      " 梨花开又去 庙门前香客拥挤",
      " 赠来一菩提 有人愁有人欢喜",
      " 跪来纵心欲 和尚看遍繁华记",
      " 祈天意 拜地去 三叩首求灵",
      " 香客们看木鱼应出生机",
      " 瞧一瞧人间一出好戏",
      " 求姻缘求得子求君相依",
      " 求一求好像都来得及",
      " 听人泪听人安听人心系",
      " 听一听什么无上奥秘",
      " 太荒诞的世界",
      " 为何还有人会着迷",
      " 神仙啊 菩萨啊 写好剧情",
      " 小弟我真的是受不起",
      " 我祈祷 我求天 保佑顺意",
      " 就是要被人称了不起",
      " 三冬暖 春不寒 此生绚丽",
      " 只愿你拥有的奢侈品",
      " 太奇幻的世界",
      " 让我们如此的着迷",
    ],
  },
  {
    title: '我们俩 - 郭顶',
    source: '../images/我们俩-郭顶.mp3',
    lyrics: [
      "你在左边 我紧靠右",
      "第一张照片",
      "不太敢亲密的",
      "属于我们俩的",
      "脸庞太天真了",
      "苹果一样带甜的羞涩",
      "太多感触",
      "已不同了",
      "世界变了",
      "还是我改变了",
      "夹在书本这相册",
      "滑落的照片让我变沉默",
      "太久 太久 是否过了太久",
      "忘了 忘了 开始怎开始的",
      "喝醉了小河边唱着歌",
      "永远爱你是我说过",
      "没有 没有 再没谁能拥有",
      "像你 像我 哭和笑都懂得",
      "再触摸",
      "我心底藏了好久",
      "那最柔软的角落",
      "你在左边 我紧靠右",
      "第一张照片",
      "不太敢亲密的",
      "属于我们俩的",
      "脸庞太天真了",
      "苹果一样带甜的羞涩",
      "太多感触",
      "已不同了",
      "世界变了",
      "还是我改变了",
      "夹在书本这相册",
      "滑落的照片让我变沉默",
      "太久 太久 是否过了太久",
      "忘了 忘了 开始怎开始的",
      "喝醉了小河边唱着歌",
      "永远爱你是我说过",
      "没有 没有 再没谁能拥有",
      "像你 像我 哭和笑都懂得",
      "再触摸",
      "我心底藏了好久",
      "那最柔软的角落",
      "太久 太久 是否过了太久",
      "忘了 忘了 开始怎么开始的",
      "喝醉了小河边唱着歌",
      "永远爱你是我说过",
      "没有 没有 再没谁能拥有",
      "像你 像我 哭和笑都懂得",
      "再触摸",
      "我心底藏了好久",
      "那最柔软的角落",
    ],
  },
  {
    title: 'So Far Away - Martin Garrix,David Guetta,Jamie Scott,Romy Dya',
    source: '../images/So Far Away-Martin Garrix,David Guetta,Jamie Scott,Romy Dya.mp3',
    lyrics: [
      "Light 'em up light 'em up",
      "Tell me where you are tell me where you are",
      "The summer nights the bright lights",
      "And the shooting stars they break my heart",
      "I'm calling you now but you're not picking up",
      "Your shadows so close if you are still in love",
      "Then light a match light a match",
      "Baby in the dark show me where you are",
      "Where you are",
      "Oh love",
      "How I miss you every single day",
      "When I see you on those streets",
      "Oh love",
      "Tell me there's a river I can swim",
      "That will bring you back to me",
      "'Cause I don't know how to love someone else",
      "I don't know how to forget your face",
      "h love",
      "God I miss you every single day",
      "And now you're so far away",
      "So far away",
      "It's breaking me I'm losing you",
      "We were far from perfect but we were worth it",
      "Too many fights and we cried",
      "But never said we're sorry",
      "Stop saying you love me",
      "You're calling me now but I can't pick up",
      "Your shadow's too close and I'm still in love",
      "The summer's over now but somehow",
      "It still breaks my heart",
      "We could have had the stars oh",
      "Oh love",
      "How I miss you every single day",
      "When I see you on those streets",
      "Oh love",
      "Tell me there's a river",
      "I can swim that will bring you back to me",
      "'Cause I don't know how to love someone else",
      "I don't know how to forget your face",
      "Oh love",
      "God I miss you every single day",
      "And now you're so far away",
      "So far away",
      "So far away",
      "Oh so far away",
      "So far away",
      "Oh love",
      "How I miss you every single day",
      "When I see you on those streets",
      "Oh love",
      "Tell me there's a river",
      "I can swim that will bring you back to me",
      "'Cause I don't know how to love someone else",
      "I don't know how to forget your face",
      "Oh love",
      "God I miss you every single day",
      "When you're so far away",
    ],
  },
  {
    title: '我要的·2022 - 旺仔小乔',
    source: '../images/我要的·2022-旺仔小乔.mp3',
    lyrics: [
      "你问我想要的是什么",
      "穿最酷的颜色",
      "oh no no 节奏放慢的生活",
      "你问我想要的是什么",
      "听我最爱的歌",
      "走遍自己的快乐",
      "呀",
      "压力像难翻的山",
      "过了一关还有一关",
      "ei 要怎么扬我的帆",
      "我那么普通那么平凡",
      "ei被生活掐住的喉",
      "又为明天发过的愁",
      "被 污染不发光的眸",
      "又被命运踩住了头",
      "那就被踩吧",
      "让我摇摆吧",
      "人生很短的",
      "我不会后退",
      "不用再揣测",
      "把我的脉搏",
      "我期待转折",
      "起码不后悔",
      "不想再失态",
      "不想再失败",
      "不想被推挤到清醒的之外",
      "站着的姿态",
      "我还是我这点永远都没人能替代",
      "不会再依赖",
      "你问我想要的是什么",
      "穿最酷的颜色",
      "oh no no 节奏放慢的生活",
      "你问我想要的是什么",
      "听我最爱的歌",
      "走遍自己的快乐",
      "画一幅岁月如梦初醒",
      "哼一曲童谣时光启迪",
      "听一段过往环绕鲸云",
      "这朱红韵律",
      "我要的音乐放肆听",
      "我要的音乐放肆听",
      "我要变成绝境中闪烁的光",
      "掉入了坑底后拉我的绳",
      "我要忘记那些所受的伤",
      "丢掉了包袱后推新的门",
      "我要砸碎那扇挡光的窗",
      "防止在黑暗中不停下沉",
      "我要扫开在门口堆积的霜",
      "探索在远处的那抹花香",
      "我要找到自己的道",
      "然后大声的告诉你我不服输",
      "看着很好笑但我的样子很坚定",
      "一直在走我的路",
      "做自己本来就不一般",
      "步伐不可能停在半山",
      "就算每次我都落单",
      "但这次没浪也要扬帆",
      "你问我想要的是什么",
      "穿最酷的颜色",
      "oh no no 节奏放慢的生活",
      "你问我想要的是什么",
      "听我最爱的歌",
      "走遍自己的快乐",
      "画一幅岁月如梦初醒",
      "哼一曲童谣时光启迪",
      "听一段过往环绕鲸云",
      "这朱红韵律",
      "我要的音乐放肆听",
    ],
  },
  {
    title: '负重一万斤长大 - 太一',
    source: '../images/负重一万斤长大-太一.mp3',
    lyrics: [
      "披头散发 很多疤 不认得我的话",
      "然而发芽 笑着花 肚子越来越大",
      "以为所见之人同自己刻意傻瓜",
      "终于因我相信的而感到了害怕",
      "有些难过 神总说 唱歌会好的多",
      "他骗人的 不是的 生而残忍的多",
      "裙子又轻舞落寞 美丽又不是她错",
      "喉咙力竭对世界爱着 在意的有谁呢",
      "如果会怜悯我",
      "又何必抓住我",
      "鬼扯，原谅恶魔",
      "咬碎牙胆怯和落寞",
      "怎么不问问我",
      "人类啊故意的",
      "为什么不偏不倚",
      "选中我一个",
      "是否会 摔碎我 摔碎我 摔碎着我",
      "是否会 可怜我 可怜我 可怜着我",
      "一会就好 让我懦弱 悄悄懦弱",
      "好不容易钻破蛋壳",
      "却看见更黑暗的家伙",
      "之后几年 她身边 仍然指指点点",
      "从未想过 最难的 就是回到从前",
      "以为曾经的玩伴会抱着取暖慰藉",
      "终于因我依赖的而学会了分别",
      "还是难过 神又说 唱歌会好得多",
      "他骗人的 不是的",
      "我已经唱哑了",
      "想开给世界的花 你教我怎么表达",
      "是不是要",
      "对着你",
      "跪下",
      "如果会怜悯我",
      "又何必抓住我",
      "鬼扯，原谅恶魔",
      "咬碎牙胆怯和落寞",
      "怎么不问问我",
      "人类啊故意的",
      "为什么不偏不倚",
      "选中我一个",
      "如果会贪恋我",
      "又何必伤害我",
      "是呢，原谅你呢",
      "负重一万斤长大着",
      "怎么不救救我",
      "人类啊可笑的",
      "为什么凋零了的",
      "不止我一个",
      "是否会",
      "拽着我",
      "掐着我",
      "撕破着我",
      "是否会",
      "勒着我",
      "咬着我",
      "扯乱着我",
      "一会就好 让我躲躲 悄悄躲躲",
      "真的有在很怀疑呢",
      "也许世界并不欢迎我",
      "披头散发",
      "很多疤",
      "不认得我的话",
      "然而发芽",
      "笑着花",
      "肚子越来越大",
      "以为所见之人同自己故意傻瓜",
      "终于因我相信的而感到了害怕",
    ],
  },
  {
    title: '在你的身边 - 盛哲',
    source: '../images/在你的身边-盛哲.mp3',
    lyrics: [
      "安静地又说分开",
      "没有依赖却是太多依赖",
      "寂寞的广场中央",
      "是谁的对白追赶我的空白",
      "爱就爱了不怕没来过",
      "恨就恨了我从没想过",
      "是怕独念一个人太深刻",
      "爱就爱了不怕没来过",
      "恨就恨了我从没想过",
      "到过的地方熟悉曾经的模样",
      "我以为忘了想念",
      "而面对夕阳希望你回到今天",
      "我记得捧你的脸",
      "在双手之间安静地看你的眼",
      "像秋天落叶温柔整个世界",
      "我想在你的身边",
      "忘了这路有多长",
      "想和你去看季节慢慢变换",
      "又来到这座广场",
      "听风随落叶已是最后一片",
      "爱就爱了不怕没来过",
      "恨就恨了我从没想过",
      "是怕独念一个人太深刻",
      "爱就爱了不怕没来过",
      "恨就恨了我从没想过",
      "到过的地方熟悉曾经的模样",
      "我以为忘了想念",
      "而面对夕阳希望你回到今天",
      "我记得捧你的脸",
      "在双手之间安静地看你的眼",
      "像秋天落叶温柔整个世界",
      "我想在你的身边",
      "我想在你的身边",
      "我想在你的身边",
      "就让那往事随风",
      "让它带走伤带走痛",
      "带回那日暮的梦",
      "花开落 云会走 铺满天",
      "而你笑着在我的身边",
      "我以为忘了想念",
      "而面对夕阳希望你回到今天",
      "我记得捧你的脸",
      "在双手之间安静地看你的眼",
      "像秋天落叶温柔整个世界",
      "我想在你的身边",
      "我想在 我想在你的身边",
      "我想在你的身边",
      "在你的身边",
    ],
  },
  {
    title: '身骑白马 - 徐佳莹',
    source: '../images/身骑白马-徐佳莹.mp3',
    lyrics: [
      "我爱谁 跨不过 从来也不觉得错",
      "自以为 抓着痛 就能往回忆里躲",
      "偏执相信着 受诅咒的水晶球",
      "阻挡可能心动的理由",
      "而你却 靠近了 逼我们视线交错",
      "原地不动 或向前走 突然在意这分钟",
      "眼前荒沙弥漫了等候 耳边传来孱弱的呼救",
      "追赶要我 爱的不保留",
      "我身骑白马 走三关",
      "我改换素衣 回中原",
      "放下西凉 无人管",
      "我一心只想 王宝钏",
      "而你却 靠近了 逼我们视线交错",
      "原地不动 或向前走 突然在意这分钟",
      "眼前荒沙弥漫了等候 耳边传来孱弱的呼救",
      "追赶要我 爱的不保留",
      "我身骑白马 走三关",
      "我改换素衣 回中原",
      "放下西凉 无人管",
      "我一心只想 王宝钏",
      "满身伤痕累累也来不及痛",
      "那是指引我走向你的清楚感受",
      "不管危不危险",
      "都要放下一切跟你走",
      "只要一起承担",
      "只要你不放手",
      "我身骑白马 走三关",
      "我改换素衣 回中原",
      "放下西凉 无人管",
      "我一心只想 王宝钏",
      "我改换素衣 回中原",
      "放下西凉 无人管",
      "我一心只想 王宝钏",
    ],
  },
  {
    title: '雾里 - 姚六一',
    source: '../images/雾里-姚六一.mp3',
    lyrics: [
      "我习惯深埋雾里",
      "自我较劲",
      "魂首分离",
      "我喜欢埋在雾里",
      "别被提起",
      "天黑再醒",
      "当白天像是电影",
      "我在这里",
      "不倦演习",
      "看上去不费力气",
      "这种境地",
      "楚歌四地",
      "对话自己似乎很容易上瘾",
      "白鸽拥抱黑鸦大胆的情景",
      "就笑我神经病我在我领地",
      "看这里一望无际",
      "彩色的世界我在我的雾里多么清晰",
      "他们黑白的心",
      "自顾自己已经有了定义",
      "何时该靠近什么应该摒弃",
      "U sound like 啊吧吧啊吧吧",
      "别争议 啊吧吧 啊吧吧",
      "我在这你的话语变得那么那么清晰",
      "破绽随处可迹",
      "在雾里",
      "Wo",
      "我随时能进雾里",
      "安心找寻",
      "遗失声音",
      "Ye别再追问我原因",
      "突然失语",
      "我的失礼",
      "我特别喜欢你今天长裙",
      "吵闹的人群保持笑容多冷静",
      "又看了一场翻炒多次的电影",
      "看这里一望无际",
      "彩色的世界我在我的雾里多么清晰",
      "他们黑白的心",
      "自顾自己已经有了定义",
      "何时该靠近什么应该摒弃",
      "U sound like 啊吧吧啊吧吧",
      "别怀疑 啊吧吧 啊吧吧",
      "我在这关上了门",
      "就能创造动人旋律堵住他们的心",
      "在雾里",
      "笑我一头雾水的你",
      "笑声来又去",
      "欣赏的人知道这词语可以是褒义",
      "我站在属于我的领域",
      "调动着思绪",
      "击穿所有未知的谜底",
      "抓要的星星",
      "所有构思伟大的诡计",
      "秘密的壮举",
      "不能实现会不会可惜",
      "别放过自己",
      "别再担心未知的问题 看这里",
      "一望无际",
      "彩色的世界我在我的雾里多么清晰",
      "他们黑白的心",
      "做好决定该怎样面对到来的危机",
      "怎样睁大眼睛",
      "Oh啊吧吧 啊吧吧",
      "笑吟吟 啊吧吧 啊吧吧",
      "我在这 游刃有余",
      "哪里需要祈祷恐惧",
      "活的像位神明",
      "在雾里 啊吧吧 啊吧吧",
      "Oh啊吧吧 啊吧吧",
      "Oh啊吧吧 啊吧吧",
      "我在这黑的白的蓝的",
      "随我定义惊艳你",
    ],
  },
  {
    title: '悬溺 - 葛东琪',
    source: '../images/悬溺-葛东琪.mp3',
    lyrics: [
      "我主张制止不了就放任",
      "这欲望与绝望之争",
      "余温她却喜欢过门",
      "临走呢",
      "还随手关了灯",
      "So funny",
      "Ya i ya i ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya i",
      "Ya i ya i ya i ya i ya i ya i ya",
      "It's so funny ya i ya i",
      "Ya i ya i ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya i",
      "It's so funny ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya i",
      "我主张克制不了就放任",
      "悬上该有的天真",
      "起伏在于喜怒哀乐",
      "松了绳",
      "大不了无人问",
      "Ya i ya i ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya i",
      "Ya i ya i ya i ya i ya i ya i ya",
      "It's so funny ya i ya i",
      "Ya i ya i ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya",
      "It's so funny ya i ya i ya i ya i ya",
      "Ya i ya i ya i ya",
      "有什么话要说",
    ],
  },
];
let currentSongIndex = 0;
window.addEventListener('scroll', function () {
  var header = document.querySelector('header');
  header.classList.toggle('sticky', window.scrollY > 0);
});
function switchSong() {
  var audioPlayer = document.getElementById('audio-player');
  currentSongIndex = (currentSongIndex + 1) % songs.length;
  audioPlayer.src = songs[currentSongIndex].source;
  updateLyrics(songs[currentSongIndex].lyrics.slice(0, songs[currentSongIndex].lyrics.length / 2),
    songs[currentSongIndex].lyrics.slice(songs[currentSongIndex].lyrics.length / 2));
  updateSongTitle(songs[currentSongIndex].title);
}
function updateLyrics(column1Content, column2Content) {
  var lyricsColumn1 = document.querySelector('.lyrics-column:nth-child(1)');
  var lyricsColumn2 = document.querySelector('.lyrics-column:nth-child(2)');

  lyricsColumn1.innerHTML = column1Content.map(line => `<p>${line}</p>`).join('');
  lyricsColumn2.innerHTML = column2Content.map(line => `<p>${line}</p>`).join('');
}
function updateSongTitle(title) {
  var songTitle = document.getElementById('song-title');
  songTitle.textContent = title;
}